# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4ecd0201249e7e7f34b17e9d233033b467f9580ff71c7dd636e894458d127b1aa1d106b27dd941300ce551cdc3b6c7a978ed2a40a8e957d79c52c2ba9d6875

test:
  secret_key_base: 5dd4b477217571cf5ad5d4cef039f804d6af7e10510ff634ba7a029cae9f69c4c4e608482de3745899ffc3273a7199dee49829198e60916f297a059ab145898f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
